import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserContextProvider } from "./Context/store";

import { useUserData } from "../lib/hooks";

import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const userData = await useUserData();

  return (
    <html lang="en">
      <body>
        <UserContextProvider>{children}</UserContextProvider>
        <Toaster />
      </body>
    </html>
  );
}
